### PR TITLE
Add contributors license agreement

### PR DESCRIPTION
**Pull request by aelse**
This PR introduces a Contributors License Agreement that will apply to all contributions to the python-crowd project. This is in line with various other open source projects (this particular CLA uses the language of the Ansible CLA).

Previously we've sought agreement from contributors to re-license the project under the BSD 2-clause license (see issue #11). I'm now asking prior contributors to agree to this CLA retroactively to their previous commits as well as future work. Note that the CLA applies in addition to the BSD 2-clause license.

If you agree then please add a comment to this issue stating so.
@ssbarnea @terinjokes @dansomething @lukecyca @akarnani

I haven't made changes to this project for a while in part due to the relation of my employment and the python-crowd module (and I feel bad about letting things slide this long). This CLA clarifies the status of contributions to this project, which helps resolve the complications in relation to my work but also in relation to the use of python-crowd (or forked works) in other projects.

### CODE REVIEW

**Comment by terinjokes** [comment]
LGTM (y)

**Comment by lukecyca** [comment]
Agreed

**Comment by dansomething** [comment]
:+1:

**Comment by akarnani** [comment]
:thumbsup:

**Comment by aelse** [comment]
Thanks all.

**Pull request merged**
